### ISSUE TITLE
Had no clouds on planet

### ISSUE THREAD

**Issue by IcArusZ4109** [themaster402/AstronomersVisualPack#1]
I play ksp on mac.
Longing for AVP for newest steam updated ksp since last vision. So I offer the highest respect to author.
But I found it doesn't work well in my game. Texture on planet did work well, but skybox was ambiguous, and the most sad thing is all kinds of clouds are disappeared.
here is my GameData folder:
![image](https://user-images.githubusercontent.com/37939629/38241921-09589928-3766-11e8-9abd-0421aad6ac90.png)
Oh, of course LoadingScreenManager doesn't work well either.

**Comment by BobTheKerbal** [comment]
try using ckan
