### ISSUE TITLE
Trouble installing it through CKAN

### ISSUE THREAD

**Issue by Brettdah** [themaster402/AstronomersVisualPack#10]
To test your mod the the impact on the performances, I wanted to try to install Astronomer's Visual Pack-2k Textures but CKAN tell me that :
"AVP-2kTextures v1.9 depends on AstronomersVisualPack, which is not compatible with the currently installed version of KSP"
I'm playing KSP 1.7.3 

And In the relationships tab I don't see the depencies listing on github too...

**Comment by themaster402** [comment]
Version metadata update has fixed this.
