### ISSUE TITLE
Extremely Slow Download Speed (under 1kB/s)

### ISSUE THREAD

**Issue by TheTalkingstreet** [themaster402/AstronomersVisualPack#11]
I experiene extremely slow download speed just on this GitHub repository. I have this problems while connected via ethernet or wifi, I have a data plan for 100 mB/s, wich I get on speedtesting sites and I got into contact with my ISP and they have no probelms. So it seems like something only you can fix.

**Comment by themaster402** [comment]
GitHub download speeds are unfortunately completely out of my hands :(
