### ISSUE TITLE
CKAN Version issue

### ISSUE THREAD

**Issue by GorgeousWalrus** [themaster402/AstronomersVisualPack#2]
When trying to install this mod via CKAN with the most recent KSP versions 1.4.1 through 1.4.4, CKAN says that the needed AstronomersVisualPack is not compatible with the KSP version. Although I couldn't find a list of version support, the title in the KSP forum suggests it is compatible with 1.4.4.

Workaround was to set 1.3 as compatible in CKAN.

**Comment by Jakaya0897** [comment]
Issue is still present in KSP Version 1.5.1.2335 It also appears some of the required mods are completely absent from CKAN atm

**Comment by 7ranceaddic7** [comment]
@GorgeousWalrus You'll want to change that workaround and set it for KSP 1.4 with that CKAN globs 1.4.*

**Comment by GorgeousWalrus** [comment]
Actually I think it might be that dependencies (or their dependecies) aren't yet compatible or not marked as compatible and therefore the whole AVP is incompatible. Did not look further into this since I've stopped playing KSP so I will leave this issue open. If this really is the case, please post it here so the issue can be closed.

**Comment by frostbytedata** [comment]
Seeing the exact same behavior with CKAN using KSP Version 1.5.1.2335 CKAN Version 1.25.4. The three texture packs show in CKAN but not the base mod.. Very strange. Let me know if I can provide more info. This is on a totally fresh install of KSP and CKAN.

**Comment by Ithendyr** [comment]
Hi, AVP compatible with 1.6.1 but depend of EnvironmentalVisualEnhancements, he's only available for 1.4.99... genius idea.

**Comment by frostbytedata** [comment]
So is this a user error, or does the Mod Owner of EVE need top update their version number?
