### ISSUE TITLE
AstornomersVisualPack causing stock textures to Z-fight

### ISSUE THREAD

**Issue by NightShift10125** [themaster402/AstronomersVisualPack#25]
I found a bug where your mod causes the stock textures to Z-fight.
I've noticed this most on flags, LVL 3 mission control, and the icons for ships, stations, landers, etc.
Testing was done on a fresh install of the game on Windows 10 and the mod was installed using CKAN. 
I was unable to find a solution but I did get some errors in the logs.

![image](https://user-images.githubusercontent.com/42304378/163267396-7072d897-a275-4bc8-a9f8-2406033f2968.png)

![image](https://user-images.githubusercontent.com/42304378/163267161-521a4496-dd16-426a-bdf7-e159eca3c51c.png)

![image](https://user-images.githubusercontent.com/42304378/163267116-7cf8b5d6-94f4-488c-8d86-75176c106be1.png)

![image](https://user-images.githubusercontent.com/42304378/163267053-fb8a81c3-3e61-4c8b-85d7-6e7a1fcd7c4a.png)

![image](https://user-images.githubusercontent.com/42304378/163266954-93b09017-0f82-4c90-9c92-f959a8583ba0.png)

**Comment by NightShift10125** [comment]
Quick update on the matter, I manually installed the mod on a fresh install of KSP.
The bug was still there.

**Comment by themaster402** [comment]
Hasn't been observed on my end, and improbable to be an issue with AVP.
