### ISSUE TITLE
TUFX profile causes bluriness with Stock Waterfall Effects

### ISSUE THREAD

**Issue by CPCTC** [themaster402/AstronomersVisualPack#26]
With AVP, TUFX, and Stock Waterfall Effects installed, a transparent blurry zone appears at the base of the Valiant engine. It's only present when AVP's TUFX profile is activated. Here's a video:

https://user-images.githubusercontent.com/63987003/163580709-179fc44d-82e3-421d-9a64-c30b95cb3f8d.mp4

When the engine is throttled up, the blur cylinder turns into a blur cone, [as shown by this person on reddit](https://old.reddit.com/r/KerbalSpaceProgram/comments/u3yu30). I have observed the same behavior.

I reproduced this on a fresh installation of KSP 1.12.3, no DLC, with only AVP, TUFX, Stock Waterfall Effects, and their dependencies installed. This `.ckan` file describes the installation:

```
{
    "spec_version": "v1.18",
    "identifier": "bug",
    "name": "bug",
    "abstract": "Stock Waterfall Effects conflicts with AstronomersVisualPack's TUFX profile.",
    "author": [
        "CPCTC"
    ],
    "version": "2022.04.15.01.36.20",
    "ksp_version_min": "1.12.3",
    "ksp_version_max": "1.12.3",
    "license": [
        "unknown"
    ],
    "depends": [
        {
            "name": "AstronomersVisualPack",
            "version": "3:v4.12"
        },
        {
            "name": "StockWaterfallEffects",
            "version": "0.6.3"
        },
        {
            "name": "TUFX",
            "version": "1.0.2.3"
        },
        {
            "name": "KabramsSunFlaresPack-Orange-High",
            "version": "001"
        },
        {
            "name": "AVP-8kTextures",
            "version": "v1.12"
        },
        {
            "name": "EnvironmentalVisualEnhancements",
            "version": "3:1.11.6.1"
        },
        {
            "name": "Scatterer",
            "version": "3:v0.0834"
        },
        {
            "name": "Scatterer-config",
            "version": "3:v0.0834"
        },
        {
            "name": "ModuleManager",
            "version": "4.2.1"
        },
        {
            "name": "B9PartSwitch",
            "version": "v2.20.0"
        },
        {
            "name": "Waterfall",
            "version": "0.8.1"
        }
    ],
    "recommends": [],
    "suggests": [],
    "kind": "metapackage",
    "release_date": "2022-04-15T09:36:20.6536433-04:00"
}
```

I'm not sure if this is even caused by AVP, so I also [reported it to Stock Waterfall Effects](https://github.com/KnightofStJohn/StockWaterfallEffects/issues/17).

If you need any more information/logs, let me know!

**Comment by AtomikkuSan** [comment]
It's possible that it could be caused by Waterfall...

**Comment by CPCTC** [comment]
I agree, it smells like a waterfall problem. I was able to reproduce this on a different TUFX profile, without AVP installed at all, so it's definitely not AVP's fault. Closing for now. If I report this somewhere else, I'll post a link here.
