### ISSUE TITLE
Sorry not really a issue but a feature request

### ISSUE THREAD

**Issue by ghost** [themaster402/AstronomersVisualPack#4]
So basicly this mod is Perfect but one thing. It doesn't add weather. Ironically I haven't been able to find a single mod that does that. If you create a weather mod it would fit perfectly with avp. Imagine lightning flashing on that green clouds as you descend into jool. Or rain and wind gusts and maybe even fog when you are flying in kerbin in or lathye!

I really appreciate it if you do this dude!
:D

**Comment by themaster402** [comment]
The _visual_ effects described are possible, however the physical effects, such as hypothetical forces on your vessel, are impossible to perform in KSP at this point in time.
