### ISSUE TITLE
No lightning on Kerbin

### ISSUE THREAD

**Issue by psychonaut25** [themaster402/AstronomersVisualPack#5]
I updated to the latest version of AVP via CKAN a couple of days ago, but ever since then, I don't have lightning on Kerbin anymore.  I decided to have a look at the lightning config file (as I usually prefer to remove lightning and aurora from Duna to make it feel more like Mars- a dead planet with no magnetosphere, etc.) and the object for Kerbin's lightning is there, it's just not appearing in-game.

I'm on KSP 1.3.1 on Windows 7 Professional 64 bit.

**Comment by psychonaut25** [comment]
Update: looks like there's no lightning on _any_ planet, not just Kerbin.

**Comment by themaster402** [comment]
Fixed in v3.81. The issue was a stray cloud object that I had forgotten to remove before issuing v3.8.

**Comment by psychonaut25** [comment]
Thanks!  I see it working now.  Cheers
